#!/bin/sh
export PATH=/usr/local/mysql/bin:~/:$PATH
cd /usr/local/mysql
chown -R mysql data/
sh mysqld_safe &
ps -ax | grep mysql
mysqladmin -u root password 509Q3z1xa
mysql -u root -p mysql < /users/dferrell/documents/shell\ scripts/create_database_dferrell2.sql

