#!/bin/sh

arg1="$1"
arg2="$2"
arg3="$3"

clear
echo "Usage: xbs [project name.xcodeproj] [app name.app] [ios platform version]"
xcodebuild -showsdks
echo
echo "executing:"
echo "xcodebuild build clean -project "$arg1".xcodeproj -sdk "$arg3" install"
echo
echo "sim launch:"
echo "iphonesim launch /local_app_build_files/UninstalledProducts/"$arg2".app 4.2 ipad &"
echo
echo "any key or break..."
read
xcodebuild build clean -project "$arg1".xcodeproj -sdk "$arg3" install

iphonesim launch /local_app_build_files/UninstalledProducts/"$arg2".app 4.2 ipad &
